### ISSUE TITLE
Không tim thấy file svd_vect_obj khi chạy lênh demo.py

### ISSUE THREAD

**Issue by quynhvan** [thanhtu98/NLP_Nhoms15_Text_Classifcation#1]

**Comment by quynhvan** [comment]
Ad ơi, ad xem giúp em lỗi này với ạ, em thấy file svd_vect_obj không có sẵn ạ

**Comment by thanhtu98** [comment]
Bạn có thể tham khảo bài viết này nhé.
https://viblo.asia/p/phan-loai-van-ban-tu-dong-bang-machine-learning-nhu-the-nao-4P856Pa1ZY3

mình làm theo bài viết này. cậu có thể xem đã thực hiện đúng theo file
redme.md chưa. vì bài này nhóm mình có 4 người làm. nên khi các bạn gửi
code cho mình chưa train thử nên kb có bug ạ

Vào Th 5, 2 thg 4, 2020 vào lúc 17:19 quynhvan <notifications@github.com>
đã viết:

**Comment by quynhvan** [comment]
Dạ, em chạy theo theo như redme thì các 3 file đầu chạy được rồi ạ. Nhưng
phần demo thì nó kêu lỗi vậy. Ad cho em xin tài liệu ad tham khảo phần code
file demo được không ạ?. Em có đọc tài liệu anh đưa rồi cả phần 1 và phần 2
mà không thấy ạ.

Vào Th 5, 2 thg 4, 2020 vào lúc 17:34 Trần Thanh Tú <
notifications@github.com> đã viết:

**Comment by thanhtu98** [comment]
ở phần feature_engineering cậu ghi cái svd_ngram ra 1 file tên là
svd_vect_obj thử xem nhé

Vào Th 5, 2 thg 4, 2020 vào lúc 18:53 quynhvan <notifications@github.com>
đã viết:

**Comment by quynhvan** [comment]
Dạ, em chạy được file demo rồi ạ. Em cảm ơn anh

Vào 0:47, Th 6, 3 thg 4, 2020 Trần Thanh Tú <notifications@github.com> đã
viết:

**Comment by thanhtu98** [comment]
ok cảm ơn cậu đã feedback nhé

**Comment by quynhvan** [comment]
Anh ơi. Trong phần code e không thấy bước Word Embeddings ạ.

Vào 13:14, Th 6, 3 thg 4, 2020 Trần Thanh Tú <notifications@github.com> đã
viết:
